In [2]:
import pandas as pd

# read CSV file using pandas.read_csv() function
df = pd.read_csv('winequality-red.csv')

In [16]:
# display first 5 rows of the dataframe
df.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5

In [17]:
# display last 5 rows of the dataframe
df.tail()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
1594,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5
1595,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,6
1596,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6
1597,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5
1598,6.0,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0,6

In [ ]:
# display summary statistics of the dataframe
df.describe()

# display information about the dataframe
df.info()

# display the number of rows and columns in the dataframe
df.shape

In [5]:
# define x and y
x = df.drop('quality', axis=1)
y = df['quality']


#y =mx+c

In [6]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error

# split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

# train and evaluate linear regression model
lr = LinearRegression()
lr.fit(X_train, y_train)
lr_pred = lr.predict(X_test)
lr_mse = mean_squared_error(y_test, lr_pred)
print('Linear Regression MSE:', lr_mse)

# train and evaluate decision tree regression model
dt = DecisionTreeRegressor(random_state=42)
dt.fit(X_train, y_train)
dt_pred = dt.predict(X_test)
dt_mse = mean_squared_error(y_test, dt_pred)
print('Decision Tree Regression MSE:', dt_mse)

# train and evaluate random forest regression model
rf = RandomForestRegressor(random_state=42)
rf.fit(X_train, y_train)
rf_pred = rf.predict(X_test)
rf_mse = mean_squared_error(y_test, rf_pred)
print('Random Forest Regression MSE:', rf_mse)

Linear Regression MSE: 0.3900251439639543
Decision Tree Regression MSE: 0.60625
Random Forest Regression MSE: 0.30123812499999997

In [18]:
# data source
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"

# Assign colum names to the dataset
col_names = ['sepal-length', 'sepal-width', 'petal-length', 'petal-width', 'Class']

# Read dataset to pandas dataframe
dataset = pd.read_csv(url, names=col_names)

In [19]:
dataset

     sepal-length  sepal-width  petal-length  petal-width           Class
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [9]:
feature_cols = ['sepal-length', 'sepal-width', 'petal-length', 'petal-width']
X = dataset[feature_cols] # Features
y = dataset.Class # Target variable

In [10]:
# split the data into training and testing sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)

In [11]:
# Scale the data
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)

X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [12]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

# create an instance of the KNeighborsClassifier class
knn = KNeighborsClassifier(n_neighbors=5)

# fit the model to the training data
knn.fit(X_train, y_train)

# predict the target variable for the test data
y_pred = knn.predict(X_test)

# evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print('KNN Accuracy:', accuracy)

KNN Accuracy: 0.9666666666666667

In [13]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
# define x and y
x = dataset.drop('Class', axis=1)
y = dataset['Class']

# split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.20)

# Scale the data
scaler = StandardScaler()
scaler.fit(X_train)

X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

# create an instance of the LogisticRegression class
logreg = LogisticRegression()

# fit the model to the training data
logreg.fit(X_train, y_train)

# predict the target variable for the test data
y_pred = logreg.predict(X_test)

# evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print('Logistic Regression Accuracy:', accuracy)

Logistic Regression Accuracy: 0.9666666666666667

In [14]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

# define x and y
x = dataset.drop('Class', axis=1)
y = dataset['Class']

# split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.20)

# Scale the data
scaler = StandardScaler()
scaler.fit(X_train)

X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

# create an instance of the SVM class
svm = SVC()

# fit the model to the training data
svm.fit(X_train, y_train)

# predict the target variable for the test data
y_pred = svm.predict(X_test)

# evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print('SVM Accuracy:', accuracy)

SVM Accuracy: 1.0

### Generally there are common steps in ML

1. Importing the libraries
2. Importing the dataset
3. visualizing the data 
4. preprocessing the data 
4. define dependent and independent variables
5. Splitting the data into training and test sets
6. fit the model
7. predict the result
8. evaluate the model

### Libraries used in machine learning

1. Numpy
2. Pandas
3. Matplotlib
4. Scikit-learn (pip install scikit-learn)